version: '3.8'
services:
  # Kafka Infrastructure
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '9101:9101'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - '8081:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  # Mỗi service một database riêng biệt
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: puchi_user
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - user_db_data:/var/lib/postgresql/data

  lesson-db:
    image: postgres:15
    container_name: lesson-db
    environment:
      POSTGRES_DB: puchi_lesson
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - lesson_db_data:/var/lib/postgresql/data

  progress-db:
    image: postgres:15
    container_name: progress-db
    environment:
      POSTGRES_DB: puchi_progress
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5434:5432'
    volumes:
      - progress_db_data:/var/lib/postgresql/data

  notification-db:
    image: postgres:15
    container_name: notification-db
    environment:
      POSTGRES_DB: puchi_notification
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5435:5432'
    volumes:
      - notification_db_data:/var/lib/postgresql/data

  analytics-db:
    image: postgres:15
    container_name: analytics-db
    environment:
      POSTGRES_DB: puchi_analytics
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5436:5432'
    volumes:
      - analytics_db_data:/var/lib/postgresql/data

  media-db:
    image: postgres:15
    container_name: media-db
    environment:
      POSTGRES_DB: puchi_media
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5437:5432'
    volumes:
      - media_db_data:/var/lib/postgresql/data

  vocabulary-db:
    image: postgres:15
    container_name: vocabulary-db
    environment:
      POSTGRES_DB: puchi_vocabulary
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5438:5432'
    volumes:
      - vocabulary_db_data:/var/lib/postgresql/data

  quiz-db:
    image: postgres:15
    container_name: quiz-db
    environment:
      POSTGRES_DB: puchi_quiz
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5439:5432'
    volumes:
      - quiz_db_data:/var/lib/postgresql/data

  api-gateway:
    build:
      context: apps/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - user-service
      - lesson-service
      - progress-service
      - notification-service
      - analytics-service
      - media-service
      - vocabulary-service
      - quiz-service
      - kafka
    environment:
      PORT: 9000
      USER_SERVICE_GRPC_URL: user-service:50051
      LESSON_SERVICE_GRPC_URL: lesson-service:50052
      PROGRESS_SERVICE_GRPC_URL: progress-service:50053
      NOTIFICATION_SERVICE_GRPC_URL: notification-service:50054
      MEDIA_SERVICE_GRPC_URL: media-service:50055
      QUIZ_SERVICE_GRPC_URL: quiz-service:50056
      VOCABULARY_SERVICE_GRPC_URL: vocabulary-service:50057
      ANALYTICS_SERVICE_GRPC_URL: analytics-service:50058
      KAFKA_BROKER: kafka:29092
    ports:
      - '9000:9000'

  user-service:
    build:
      context: apps/user-service
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      - user-db
      - kafka
    environment:
      DATABASE_URL: ${USER_SERVICE_DATABASE_URL}
      KAFKA_BROKER: kafka:29092

  lesson-service:
    build:
      context: apps/lesson-service
      dockerfile: Dockerfile
    container_name: lesson-service
    depends_on:
      - lesson-db
      - kafka
    environment:
      DATABASE_URL: ${LESSON_SERVICE_DATABASE_URL}
      KAFKA_BROKER: kafka:29092

  progress-service:
    build:
      context: apps/progress-service
      dockerfile: Dockerfile
    container_name: progress-service
    depends_on:
      - progress-db
      - kafka
    environment:
      DATABASE_URL: ${PROGRESS_SERVICE_DATABASE_URL}
      KAFKA_BROKER: kafka:29092

  notification-service:
    build:
      context: apps/notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    depends_on:
      - notification-db
      - kafka
    environment:
      DATABASE_URL: ${NOTIFICATION_SERVICE_DATABASE_URL}
      KAFKA_BROKER: kafka:29092

  analytics-service:
    build:
      context: apps/analytics-service
      dockerfile: Dockerfile
    container_name: analytics-service
    depends_on:
      - analytics-db
      - kafka
    environment:
      DATABASE_URL: ${ANALYTICS_SERVICE_DATABASE_URL}
      KAFKA_BROKER: kafka:29092

  media-service:
    build:
      context: apps/media-service
      dockerfile: Dockerfile
    container_name: media-service
    depends_on:
      - media-db
      - kafka
    environment:
      DATABASE_URL: ${MEDIA_SERVICE_DATABASE_URL}
      KAFKA_BROKER: kafka:29092

  vocabulary-service:
    build:
      context: apps/vocabulary-service
      dockerfile: Dockerfile
    container_name: vocabulary-service
    depends_on:
      - vocabulary-db
      - kafka
    environment:
      DATABASE_URL: ${VOCABULARY_SERVICE_DATABASE_URL}
      KAFKA_BROKER: kafka:29092

  quiz-service:
    build:
      context: apps/quiz-service
      dockerfile: Dockerfile
    container_name: quiz-service
    depends_on:
      - quiz-db
      - kafka
    environment:
      DATABASE_URL: ${QUIZ_SERVICE_DATABASE_URL}
      KAFKA_BROKER: kafka:29092

volumes:
  user_db_data:
  lesson_db_data:
  progress_db_data:
  notification_db_data:
  analytics_db_data:
  media_db_data:
  vocabulary_db_data:
  quiz_db_data:
