version: '3.8'
services:
  # Kafka Infrastructure
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '9101:9101'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - '8080:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  # Mỗi service một database riêng biệt
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: puchi_user
      POSTGRES_USER: puchi_user
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    volumes:
      - user_db_data:/var/lib/postgresql/data

  lesson-db:
    image: postgres:15
    container_name: lesson-db
    environment:
      POSTGRES_DB: puchi_lesson
      POSTGRES_USER: puchi_user
      POSTGRES_PASSWORD: 123456
    ports:
      - '5433:5432'
    volumes:
      - lesson_db_data:/var/lib/postgresql/data

  progress-db:
    image: postgres:15
    container_name: progress-db
    environment:
      POSTGRES_DB: puchi_progress
      POSTGRES_USER: puchi_user
      POSTGRES_PASSWORD: 123456
    ports:
      - '5434:5432'
    volumes:
      - progress_db_data:/var/lib/postgresql/data

  notification-db:
    image: postgres:15
    container_name: notification-db
    environment:
      POSTGRES_DB: puchi_notification
      POSTGRES_USER: puchi_user
      POSTGRES_PASSWORD: 123456
    ports:
      - '5435:5432'
    volumes:
      - notification_db_data:/var/lib/postgresql/data

  analytics-db:
    image: postgres:15
    container_name: analytics-db
    environment:
      POSTGRES_DB: puchi_analytics
      POSTGRES_USER: puchi_user
      POSTGRES_PASSWORD: 123456
    ports:
      - '5436:5432'
    volumes:
      - analytics_db_data:/var/lib/postgresql/data

  media-db:
    image: postgres:15
    container_name: media-db
    environment:
      POSTGRES_DB: puchi_media
      POSTGRES_USER: puchi_user
      POSTGRES_PASSWORD: 123456
    ports:
      - '5437:5432'
    volumes:
      - media_db_data:/var/lib/postgresql/data

  vocabulary-db:
    image: postgres:15
    container_name: vocabulary-db
    environment:
      POSTGRES_DB: puchi_vocabulary
      POSTGRES_USER: puchi_user
      POSTGRES_PASSWORD: 123456
    ports:
      - '5438:5432'
    volumes:
      - vocabulary_db_data:/var/lib/postgresql/data

  quiz-db:
    image: postgres:15
    container_name: quiz-db
    environment:
      POSTGRES_DB: puchi_quiz
      POSTGRES_USER: puchi_user
      POSTGRES_PASSWORD: 123456
    ports:
      - '5439:5432'
    volumes:
      - quiz_db_data:/var/lib/postgresql/data

volumes:
  user_db_data:
  lesson_db_data:
  progress_db_data:
  notification_db_data:
  analytics_db_data:
  media_db_data:
  vocabulary_db_data:
  quiz_db_data:
