# Kafka Infrastructure - Sử dụng Bitnami Kafka với KRaft mode
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - name: kafka-9092
      port: 9092
      targetPort: 9092
    - name: kafka-29092
      port: 29092
      targetPort: 29092
    - name: kafka-jmx
      port: 9101
      targetPort: 9101
    - name: kafka-controller
      port: 9093
      targetPort: 9093
  selector:
    app: kafka
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 29092
            - containerPort: 9101
            - containerPort: 9093
          env:
            # KRaft mode configuration
            - name: KAFKA_ENABLE_KRAFT
              value: 'yes'
            - name: KAFKA_CFG_NODE_ID
              value: '1'
            - name: KAFKA_CFG_PROCESS_ROLES
              value: 'broker,controller'
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: '1@kafka:9093'
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: 'CONTROLLER'
            # Listener configuration
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
            - name: KAFKA_CFG_LISTENERS
              value: 'PLAINTEXT://:9092,CONTROLLER://:9093'
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: 'PLAINTEXT://kafka:29092'
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: 'PLAINTEXT'
            # Development settings
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: 'true'
            - name: KAFKA_CFG_DELETE_TOPIC_ENABLE
              value: 'true'
            - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: '1'
            - name: KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR
              value: '1'
            - name: KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: '1'
            - name: KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: '0'
            # JMX monitoring
            - name: KAFKA_CFG_JMX_PORT
              value: '9101'
            - name: KAFKA_CFG_JMX_HOSTNAME
              value: 'localhost'
            # Security (cho phép plaintext trong development)
            - name: ALLOW_PLAINTEXT_LISTENER
              value: 'yes'
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - kafka-topics.sh --bootstrap-server localhost:9092 --list
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - kafka-topics.sh --bootstrap-server localhost:9092 --list
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: kafka-data
          emptyDir: {}
