---
# Lesson Service Database
apiVersion: v1
kind: Service
metadata:
  name: lesson-db
  namespace: puchi
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: lesson-db
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lesson-db
  namespace: puchi
spec:
  serviceName: lesson-db
  replicas: 1
  selector:
    matchLabels:
      app: lesson-db
  template:
    metadata:
      labels:
        app: lesson-db
    spec:
      containers:
        - name: lesson-db
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: puchi_lesson_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - name: lesson-db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: lesson-db-data
      spec:
        accessModes: ['ReadWriteOnce']
        storageClassName: puchi-storage
        resources:
          requests:
            storage: 1Gi
