---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: puchi-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: puchi-storage
  hostPath:
    path: /data/user-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lesson-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: puchi-storage
  hostPath:
    path: /data/lesson-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: progress-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: puchi-storage
  hostPath:
    path: /data/progress-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: notification-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: puchi-storage
  hostPath:
    path: /data/notification-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: analytics-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: puchi-storage
  hostPath:
    path: /data/analytics-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: puchi-storage
  hostPath:
    path: /data/media-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vocabulary-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: puchi-storage
  hostPath:
    path: /data/vocabulary-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: quiz-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: puchi-storage
  hostPath:
    path: /data/quiz-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: puchi-storage
  hostPath:
    path: /data/kafka
