apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: puchi
type: Opaque
data:
  API_KEY: TnlBOXVPV2NpbEIyMW9XN0FlcUdWR08zdU0zMTZLb0U=
  DB_PASSWORD: MTIzNDU2
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: puchi
type: Opaque
data:
  username: cHVjaGlfdXNlcg== # "puchi_user" (base64)
  password: MTIzNDU2 # "123456" (base64)
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: puchi
type: Opaque
data:
  username: bW9uZ29fcm9vdA== # "mongo_root" (base64)
  password: MTIzNDU2 # "123456" (base64)
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
  namespace: puchi
type: Opaque
data:
  tunnel-token: ZXlKaElqb2lPR1JoWmpBMFpEbG1NMkV5WVRJMlpEazVOalkyTVdJellUWTNaRGczTVRBaUxDSjBJam9pTm1Ka01ERmxOVEF0WXpNNFppMDBNVFZtTFdJMU5Ea3RaR0kwTkRJNE1HTTVaRFk0SWl3aWN5STZJazE2U1RGUFZFWm9UVEpGZEZsVVVUQmFhVEF3VDFSSk5VeFVaelZQUjAxMFdtMUthRTlVWjNsWmFtTTBUbGRGTXlKOQ== # ví dụ, thay bằng token thật đã encode base64
---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: puchi
type: Opaque
data:
  SESSION_SECRET: c3VwZXJsb25nc2Vzc2lvbnNlY3JldGtleTEyMzQ1Ng== # superlongsessionsecretkey123456
  ENCRYPTION_KEY: c3VwZXJsb25nZW5jcnlwdGlvbmtleTEyMzQ1Ng== # superlongencryptionkey123456
  JWT_SECRET: and0X3NlY3JldF9leGFtcGxl # jwt_secret_example
