# Service cho các microservice
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: puchi
spec:
  selector:
    app: user-service
  ports:
    - port: 50051
      targetPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: lesson-service
  namespace: puchi
spec:
  selector:
    app: lesson-service
  ports:
    - port: 50052
      targetPort: 50052
---
apiVersion: v1
kind: Service
metadata:
  name: progress-service
  namespace: puchi
spec:
  selector:
    app: progress-service
  ports:
    - port: 50053
      targetPort: 50053
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: puchi
spec:
  selector:
    app: notification-service
  ports:
    - port: 50054
      targetPort: 50054
---
apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: puchi
spec:
  selector:
    app: media-service
  ports:
    - port: 50055
      targetPort: 50055
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-service
  namespace: puchi
spec:
  selector:
    app: quiz-service
  ports:
    - port: 50056
      targetPort: 50056
---
apiVersion: v1
kind: Service
metadata:
  name: vocabulary-service
  namespace: puchi
spec:
  selector:
    app: vocabulary-service
  ports:
    - port: 50057
      targetPort: 50057
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: puchi
spec:
  selector:
    app: analytics-service
  ports:
    - port: 50058
      targetPort: 50058 